name: Build/release

on:
  push:
    tags:
      - v*
  workflow_dispatch:


jobs:
  release:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build/release Electron app
        run: npx electron-builder --publish=always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
